### ISSUE TITLE
Generate model classes 

### ISSUE THREAD

**Issue by eduard93** [lscalese/OpenAPI-Client-Gen#1]
Generate model classes (in Petstore example - `ApiResponse`, `Category`, `Pet`, `Tag`, `Order`, `User`) and:
- refer to them in `bodybody` property instead of `%Stream.GlobalBinary`
- return them as a parsed response instead of  `%Stream.GlobalBinary`

**Comment by eduard93** [comment]
Here's an article on the reverse action: https://community.intersystems.com/post/generate-swagger-spec-persistent-and-serial-classes

**Comment by lscalese** [comment]
Guillaume Rongier has developped which could be used in this application.
https://github.com/grongierisc/objectscript-openapi-definition
I'll try to use and include this.

**Comment by lscalese** [comment]
Ok, It's done for changing bodybody to Pet, etc using the library https://github.com/grongierisc/objectscript-openapi-definition
I processed the generated models to add %Persistent and %XML.Adaptor super class.
Now, I must enhance the response.

**Comment by lscalese** [comment]
Hi @eduard93 ,

I enhanced the response management to load a model from %Net.HttpResponse (If the model is defined in response "200").
The parsing is in Utils classmethod processParsedResponse.

For the performance perhaps I'll move this to ParsedResponse subclasses.
It will avoid to use $Property and $Method.
