### ISSUE TITLE
YAML support?

### ISSUE THREAD

**Issue by bdeboe** [lscalese/OpenAPI-Client-Gen#14]
Any chance you can make this work with a YAML spec as well? I'm sure there'll be an easy converter utility somewhere...

I was hoping I could easily test this with the IRIS NLP REST APIs ([ancient article here](https://community.intersystems.com/post/accessing-iknow-rest-apis-20171)) by simply pointing it at http://localhost:52773/api/iKnow/latest/USER/swagger

**Comment by bdeboe** [comment]
for completeness: it does fail when I try with YAML instead of JSON swagger:

```
ERROR #5002: ObjectScript error: <INVALID OREF>ztranslateSpec+1^dc.openapi.client.Spec.1
```

**Comment by eduard93** [comment]
I use https://editor.swagger.io/ to convert between formats.

**Comment by lscalese** [comment]
Hi @eduard93, @bdeboe ,
Yes, There is a lot of online tools to convert a YAML to JSON.
ex : [https://onlineyamltools.com/convert-yaml-to-json](https://onlineyamltools.com/convert-yaml-to-json)

I'll check if I can include a tool for the convert.

About `ERROR #5002: ObjectScript error: <INVALID OREF>ztranslateSpec+1^dc.openapi.client.Spec.1`.
I add validation soon.

**Comment by lscalese** [comment]
@bdeboe 
I commit an error handler for an unsupported version and format.
The fix will be included in version 1.0.2

**Comment by lscalese** [comment]
@bdeboe 
Version 1.0.2 is released.

For the conversion YAML to JSON:

I don't want to force users to install external software.
With docker, I could script the install but for others users it's a problem.

Depend on a online service is not the best way.

I think we should develop a YAML to JSON converter in ObjectScript.
Perhaps an idea for an open exchange app.
And then it could be included in this project as a dependency.

**Comment by lscalese** [comment]
There is yq software.
I'll do a test: https://mikefarah.gitbook.io/yq/

**Comment by eduard93** [comment]
Yes, bidirectional YAML<->DynamicObject converter in ObjectScript would be nice. 

But I suppose it's a separate project.

**Comment by bdeboe** [comment]
indeed separate (has much broader use), but it shouldn't be too hard :-)

**Comment by bdeboe** [comment]
you really got me triggered to try and turn the NLP REST API into a production so I spent my morning coffee on it :-)

https://github.com/bdeboe/isc-yaml-utils

**Comment by lscalese** [comment]
Nice !
I try ASAP.

**Comment by lscalese** [comment]
@bdeboe ,
Fyi, I try to generate from NLP Swagger spec converted in json and there is a generation error.
I will attempt to fix it after my working day.
