### ISSUE TITLE
operationId mandatory

### ISSUE THREAD

**Issue by wdrost** [lscalese/OpenAPI-Client-Gen#15]
operationID is being used in the Generator class, but thid is an optional item in Open API. When this field is not in the spec file, the generator fails, as it's used a a subscript value, which cannot be empty/null

**Comment by lscalese** [comment]
Hello @wdrost,
Thanks for the feed back, I add a fix soon.

**Comment by lscalese** [comment]
@wdrost   We need a unique identifier.
If he does not exists, I build a unique string.
For testing purposes, can you send me your specification file, please ?
Thank you.

**Comment by wdrost** [comment]
The file I'm testing is the spec for the national provider iondex in the Netherlands:

[vzvz_zorg_ab_v2_6_3_oas_20200727.zip](https://github.com/lscalese/OpenAPI-Client-Gen/files/5547966/vzvz_zorg_ab_v2_6_3_oas_20200727.zip)

**Comment by lscalese** [comment]
Thank you for sharing!
I found another problem and I'm going to fix it.

**Comment by lscalese** [comment]
It's done.  fix included in version 1.0.2.
