### ISSUE TITLE
Add route to Swagger spec in Rest Proxy service

### ISSUE THREAD

**Issue by wdrost** [lscalese/OpenAPI-Client-Gen#18]
Would be helpfull to have an additional route in the generated Rest class for access to the swagger spec:
Something like this:

<Route Url="/_spec" Method="get" Call="SwaggerSpec" />
</Routes>
}

ClassMethod SwaggerSpec() As %Status
{
    Try {
        Do ##class(%REST.Impl).%SetContentType("application/json")
        If '##class(%REST.Impl).%CheckAccepts("application/json") Do ##class(%REST.Impl).%ReportRESTError(..#HTTP406NOTACCEPTABLE,$$$ERROR($$$RESTBadAccepts)) Quit
        
		Set xDataTemplate = ##class(%Dictionary.XDataDefinition).%OpenId("xxxxxx.model.spec"_"||OpenAPI",,.sc)
		
		Set swagger = ##class(%DynamicObject).%FromJSON(xDataTemplate.Data)
		Set swagger.basePath = "/xxxxxxx"
   		Set swagger.host = %request.CgiEnvs("SERVER_NAME") _ ":" _ %request.CgiEnvs("SERVER_PORT") ;"localhost:52773"
        Do ##class(%REST.Impl).%WriteResponse(swagger.%ToJSON())
    } Catch (ex) {
        Do ##class(%REST.Impl).%ReportRESTError(..#HTTP500INTERNALSERVERERROR,ex.AsStatus(),$parameter("dc.openapi.client.api.impl","ExposeServerExceptions"))
    }
    Quit $$$OK
}

**Comment by lscalese** [comment]
Hello @wdrost,

Yes, I add the spec.

In this case, it's not an app generated with do ^%REST, implementation will be a little bit different :-)

**Comment by lscalese** [comment]
@wdrost 
Yessss, It works !

the route is `/<webapp>/_spec`

It will be included in 1.2+ release. commit already done on Master.
