### ISSUE TITLE
Split generated classes into subpackages

### ISSUE THREAD

**Issue by eduard93** [lscalese/OpenAPI-Client-Gen#2]
Currently all classes are generated in one package, which can be hard to make sense of for a user. I propose the following subpackages:
- `model` – data classes from #1 
- `msg` – requests and responses
- `bs` – Business services
- `bp` – Business Processes
- `bo` – Business Operations
- `rest` – REST handlers, spec

`Production`, `Utils` classes can stay in root package

**Comment by lscalese** [comment]
Yes, I agree.
Go Go Go.

**Comment by lscalese** [comment]
Done!
