### ISSUE TITLE
Centralize HttpRequest creation in BO

### ISSUE THREAD

**Issue by eduard93** [lscalese/OpenAPI-Client-Gen#3]
Move `%Net.HttpRequest` creation in BO methods into a separate method `GetRequest` and call it from operation requests. Why:
- Very often APIs require HTTPS or some custom header. If request is produced from `GetRequest` it’s easy to modify it for all requests.
- Request object reuse. To achieve better throughput it’s usually preferable to use the same `%Net.HttpRequest` object. `GetRequest` can easily implement cache logic if required by user

Also move `Do pHttpRequestIn.SetHeader("accept", pRequest.accept)` into `GetRequest` method.

**Comment by lscalese** [comment]
Yes, you're right!
It's done.
