### ISSUE TITLE
WebSwaggerValidator returns 404

### ISSUE THREAD

**Issue by eduard93** [lscalese/OpenAPI-Client-Gen#35]
Calling `dc.openapi.client.Spec:generateApp` gets to `dc.swaggervalidatorcli.WebSwaggerValidator:Parse` which sends `POST /validator/parse` request which returns 404.

**Comment by lscalese** [comment]
Hi @eduard93 ,
Thank you for your report, I check it as soon as possible.
If I can't check that today, It will be after the Global Summit.

**Comment by lscalese** [comment]
Hi @eduard93 ,

I rebuild the project yesterday evening and unit tests result to an error ...
I have to analyse what happened.  

However, I cannot reproduce the error 404 with /validator/parse.
The validator uses the public REST services [https://validator.swagger.io/](https://validator.swagger.io/) by default.
Can you reproduce the problem again?  If yes, could you please send more details to reproduce this error?

Thank you!
Lorenzo.

**Comment by lscalese** [comment]
The unit test error is identified.
This is a problem with a class copy (using merge ^oddDEF).
I changed to use "%ConstructClone" of %Dictionary.ClassDefintion and it works.  
I will push a new version asap.

**Comment by lscalese** [comment]
Fix in version 2.1.1 (pushed to OEX - IPM).  Le me know if the 404 persists or If we can close this issue.
Thank you.

**Comment by eduard93** [comment]
Thank you
