### ISSUE TITLE
Stream copying

### ISSUE THREAD

**Issue by eduard93** [lscalese/OpenAPI-Client-Gen#4]
In bo `bodybody` stream is copied like this:
````
Do pRequest.bodybody.Rewind()
While 'pRequest.bodybody.AtEnd {
		Do pHttpRequestIn.EntityBody.Write(pRequest.bodybody.Read())
}
````

It can be simplified with:
`Do pHttpRequestIn.EntityBody.CopyFrom(pRequest.bodybody)`

After #1 is implemented it can be replaced with:
`set sc = pRequest.bodybody %ToJSON(pHttpRequestIn.EntityBody)`

**Comment by lscalese** [comment]
Yes, of course!
It's due to a test with a $zconvert on each read.
I'll change that.

**Comment by lscalese** [comment]
Done.
