### ISSUE TITLE
Replace zn "namespace" with set $namespace = "namespace"

### ISSUE THREAD

**Issue by eduard93** [lscalese/OpenAPI-Client-Gen#6]
zn is used in `Projection` class.

Replacing 
```
zn "namespace" 
```
with 
```
set $namespace = "namespace"
```
automatically returns to the previous namespace on a frame stack pop.

**Comment by lscalese** [comment]
Thanks for the feedback @eduard93 !
I read the documentation (https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=RCOS_vnamespace) and replace zn by new $namespace  Set $namespace ...

**Comment by lscalese** [comment]
New $namespace
	Set oldNs = $namespace
	Set $namespace = "%SYS"
	if ##class(Security.Applications).Exists("/petshoprest") { Quit $$$OK }
	write "Create web application ...",!
	set webName = "/petshoprest"
	set webProperties("NameSpace") = oldNs
	set webProperties("Enabled") = 1
	set webProperties("CSPZENEnabled") = 1
	set webProperties("AutheEnabled") = 64
	set webProperties("iKnowEnabled") = 1
	set webProperties("DeepSeeEnabled") = 1
	Set webProperties("DispatchClass")="petshop.REST"
	Set webProperties("MatchRoles")=":%DB_IRISAPP"
	set sc = ##class(Security.Applications).Create(webName, .webProperties)
	write !,"Web application creation status ", $SYSTEM.Status.GetOneErrorText(sc),! 
	Quit $$$OK

**Comment by lscalese** [comment]
I guess it would be considered as fixed.
