### ISSUE TITLE
Error on generation

### ISSUE THREAD

**Issue by eduard93** [lscalese/OpenAPI-Client-Gen#7]
I'm executing this code:
```
Set sc = ##class(dc.openapi.client.Spec).generateApp("petshop", "https://petstore.swagger.io:443/v2/swagger.json")
```
and getting this error:
```
ERROR #5002: Error: <CLASS DOES NOT EXIST>zmodels+2^dc.openapi.client.Generator.1 *Grongier.OpenApi.Definition
```

Looks like `Grongier.OpenApi.Definition` class is not in repo: https://github.com/lscalese/OpenAPI-Client-Gen/blob/master/src/dc/openapi/client/Generator.cls#L173

**Comment by lscalese** [comment]
Hi @eduard93,

Can you rebuild the image and retry : 
docker-compose build --no-cache

iris.script has changed to install objectscript-openapi-definition

Thank you.

**Comment by eduard93** [comment]
I'm not using docker - just installing on host.

After running:
```
 zpm "install sslclient"
 zpm "install objectscript-openapi-definition"
 zpm "install swagger-ui"
```
It works now.

Also got web app compilation error: Web application creation status Error #879: Role %DB_IRISAPP does not exist


I think it's caused by: https://github.com/lscalese/OpenAPI-Client-Gen/blob/76fcb96b2fc2ed239dc0efab37efa51ab489f18c/src/dc/openapi/client/Generator.cls#L252

**Comment by lscalese** [comment]
Hoooo Yes, sorry for that...
I solve this with %DB related to the namespace installation.

**Comment by lscalese** [comment]
May I consider this issue as fixed and close?

**Comment by eduard93** [comment]
Sure!

**Comment by lscalese** [comment]
Thank you!
