### ISSUE TITLE
Generation problem with operationId or definitions contains "_" 

### ISSUE THREAD

**Issue by lscalese** [lscalese/OpenAPI-Client-Gen#8]
Char "_" is not allowed for Method, Property or ClassName.
Specification contains this character must be translated to avoid a generation error.

**Comment by lscalese** [comment]
This issue is fixed by a translation of the specification file.
Comments or advice about a better way are welcome :-)
[Spec class](https://github.com/lscalese/OpenAPI-Client-Gen/blob/master/src/dc/openapi/client/Spec.cls#L134)

**Comment by lscalese** [comment]
Every method, property or class name are translated by this [name method](https://github.com/lscalese/OpenAPI-Client-Gen/blob/master/src/dc/openapi/client/Generator.cls#L95).  To avoid the open problem with [openapi-definition](https://github.com/grongierisc/objectscript-openapi-definition/issues/4) the specification translation is currently kept.

**Comment by eduard93** [comment]
@lscalese maybe `%JSONFIELDNAME` can be a better workaround?

For example:

```
Class sample.Contact Extends %Persistent,Ens.Request, %JSON.Adaptor {

Property phoneNum As %VarString(%JSONFIELDNAME="phone_Num");
}
```

This way:
- IRIS works with `phoneNum`
- Call to `%ToJSON` produces `{"phone_Num":"123456789"}`
- Call to `%FromJSON` accepts `{"phone_Num":"123456789"}`

**Comment by lscalese** [comment]
Thank you for the tips @eduard93 ! :-)

After a second verification, the problem with model generation is not the property name but the class name.
Sometimes, we have something like that ` "$ref":"#Definition/a_name_with_underscore"`

I'll fork https://github.com/grongierisc/objectscript-openapi-definition
I think the problem could be fixed by a $translate on three lines : 

1. https://github.com/grongierisc/objectscript-openapi-definition/blob/master/src/Grongier/OpenApi/Definition.cls#L24
2. https://github.com/grongierisc/objectscript-openapi-definition/blob/master/src/Grongier/OpenApi/Definition.cls#L170
3. https://github.com/grongierisc/objectscript-openapi-definition/blob/master/src/Grongier/OpenApi/Definition.cls#L176

Edit: So ... I can see Guillaume has the same idea and then He rollback : 
https://github.com/lscalese/objectscript-openapi-definition/commit/b9e97e06a6fe8d9ef965c6efd217f89dc06ac9de
I'll discuss with him to know the rollback reason.

**Comment by lscalese** [comment]
discussion will continue on objectscript-openapi-definition project.
